/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend;

import classes.Resource;
import classes.Task;
import classes.Version;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Timer;

/**
 *
 * @author l0011
 */
public class AddTask extends javax.swing.JFrame {

    /**
     * Instance fields
     */
    private CreateVersionScreen previousScreen;
    private Version version;
    private Task task;
    
    /** Creates new form AddTask 
     */
    public AddTask() {
        initComponents();
    }
    
    /** Creates new form AddTask
     * @param previous 
     * @param version 
     */
    public AddTask(CreateVersionScreen previous, Version version) {
        initComponents();
        previousScreen = previous;
        this.version = version;
        task = null;
        populateFields();
    }
    
    private void populateFields(){
        if(version.getTasks().isEmpty())
            taskStartField.setText(version.getStartDate().toString());
        else
            taskStartField.setText(version.getLastTask().getEndDate().toString());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskBackBtn = new javax.swing.JButton();
        addTaskBtn = new javax.swing.JButton();
        taskCostField = new javax.swing.JTextField();
        taskEndField = new javax.swing.JTextField();
        taskStartField = new javax.swing.JTextField();
        taskNameField = new javax.swing.JTextField();
        taskTypeField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        taskResources = new javax.swing.JComboBox<>();
        taskDurationField = new javax.swing.JTextField();
        taskAddResourceBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        taskBackBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        taskBackBtn.setText("Back to Menu");
        taskBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskBackBtnActionPerformed(evt);
            }
        });

        addTaskBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addTaskBtn.setText("Add Task");
        addTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskBtnActionPerformed(evt);
            }
        });

        taskCostField.setEnabled(false);
        taskCostField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskCostFieldActionPerformed(evt);
            }
        });

        taskEndField.setEnabled(false);
        taskEndField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskEndFieldActionPerformed(evt);
            }
        });

        taskStartField.setEnabled(false);
        taskStartField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskStartFieldActionPerformed(evt);
            }
        });

        taskNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskNameFieldActionPerformed(evt);
            }
        });

        taskTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskTypeFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Task");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Type");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Duration");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Start Date");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("End Date");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Cost");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/task.jpg"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Resource");

        taskResources.setModel(new DefaultComboBoxModel(Resource.enumsToStringArray()));

        taskDurationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskDurationFieldActionPerformed(evt);
            }
        });

        taskAddResourceBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        taskAddResourceBtn.setText("Add Another Resource");
        taskAddResourceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskAddResourceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(taskEndField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(taskStartField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(taskTypeField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(taskNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(taskCostField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(taskResources, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(taskDurationField))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(taskBackBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addTaskBtn)))
                    .addComponent(taskAddResourceBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(taskNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(taskTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taskDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(taskStartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(taskEndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(taskCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(taskResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(taskAddResourceBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taskBackBtn)
                            .addComponent(addTaskBtn)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taskBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskBackBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if(task != null){
            previousScreen.getVersionEndField().setText(task.getEndDate().toString());
            previousScreen.getVersionCostField().setText(String.valueOf(task.getCost()));
            previousScreen.getVersionDurationField().setText(String.valueOf(task.getDuration()));
            previousScreen.getVersionTasksField().setText(String.valueOf(version.getNumTasks()));
        }
        previousScreen.setVisible(true);
    }//GEN-LAST:event_taskBackBtnActionPerformed

    private void addTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskBtnActionPerformed
        String name, type, startDate;
        double duration;
        try {
            name = taskNameField.getText();
            type = taskTypeField.getText();
            if (version.getTasks().isEmpty()) {
                startDate = version.getStartDate().toString();
            } else {
                startDate = version.getLastTask().getEndDate().toString();
            }
            taskStartField.setText(startDate);
            duration = Double.parseDouble(taskStartField.getText());
            String res = (String) taskResources.getSelectedItem();
            System.out.println(res);
            task = new Task(name, type, startDate, duration, res);
            version.addTask(task);
            version.printTasks();
            taskEndField.setText(task.getEndDate().toString());
            taskCostField.setText(String.valueOf(task.getCost()));

            Timer delay = new Timer(3000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    taskNameField.setText("");
                    taskTypeField.setText("");
                    taskStartField.setText(task.getEndDate().toString());
                    taskEndField.setText("");
                    taskCostField.setText("");
                    taskNameField.requestFocusInWindow();
                }
            });
            delay.setRepeats(false);
            delay.start();

        } catch (NumberFormatException e) {
            System.out.println("Something wrong with the number " + e.getMessage());
        } catch (Exception e) {
            System.out.println("Or something else happeneing " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_addTaskBtnActionPerformed

    private void taskCostFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskCostFieldActionPerformed
        addTaskBtn.requestFocusInWindow();
    }//GEN-LAST:event_taskCostFieldActionPerformed

    private void taskEndFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskEndFieldActionPerformed
        taskCostField.requestFocusInWindow();
    }//GEN-LAST:event_taskEndFieldActionPerformed

    private void taskStartFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskStartFieldActionPerformed
        taskEndField.requestFocusInWindow();
    }//GEN-LAST:event_taskStartFieldActionPerformed

    private void taskNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskNameFieldActionPerformed
        taskTypeField.requestFocus();
    }//GEN-LAST:event_taskNameFieldActionPerformed

    private void taskTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskTypeFieldActionPerformed
        taskStartField.requestFocusInWindow();
    }//GEN-LAST:event_taskTypeFieldActionPerformed

    private void taskDurationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskDurationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskDurationFieldActionPerformed

    private void taskAddResourceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskAddResourceBtnActionPerformed
        // TODO add your handling code here:
        String name, type, start, resource;
        double duration;
        if(task == null){
            name = taskNameField.getText();
            type = taskTypeField.getText();
            duration = Double.parseDouble(taskDurationField.getText());
            start = taskStartField.getText();
            resource = (String)taskResources.getSelectedItem();
            
        }
            
    }//GEN-LAST:event_taskAddResourceBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AddTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTaskBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton taskAddResourceBtn;
    private javax.swing.JButton taskBackBtn;
    private javax.swing.JTextField taskCostField;
    private javax.swing.JTextField taskDurationField;
    private javax.swing.JTextField taskEndField;
    private javax.swing.JTextField taskNameField;
    private javax.swing.JComboBox<String> taskResources;
    private javax.swing.JTextField taskStartField;
    private javax.swing.JTextField taskTypeField;
    // End of variables declaration//GEN-END:variables

}
